apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: andyyelinhu/world-cup-demo:andydb
          env:
            - name: MARIA_HOST
              value: 'db-service.demo.svc.cluster.local'
            - name: MARIA_USER
              value: root
            - name: MARIA_PASS
              valueFrom:
                secretKeyRef:
                  name: quick-pass
                  key: password
            - name: WELCOME
              value: Welcome to FIFA World Cup 2022!! Lets talk about semifinalists ...
      #     volumeMounts:
      #       - name: app-src
      #         mountPath: /app/app.py
      # volumes:
      #   - name: app-src
      #     emptyDir: {}
