apiVersion: v1
kind: Secret
metadata:
  name: quick-pass
  namespace: demo
type: Opaque
data:
  password: QW5keUh1MTExMSE=

# 2 problems, secret has to be the one I found?, 2 initializing data doesnt work
# where was the original secret generated, how is the password set?, why there was no port in app.py, is the host value right? what should go in the host?