apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: andyyelinhu/world-cup-demo:latest
          env:
            - name: MARIA_USER
              value: root
            - name: MARIA_PASS
              valueFrom:
                secretKeyRef:
                  name: quickstart-maria-pass
                  key: token
            - name: WELCOME
              value: Welcome to FIFA World Cup 2022!! Lets talk about semifinalists ...
            - name: FLASK_ENV
                value: "development"
          volumeMounts:
            - name: app-src
              mountPath: /app
      volumes:
        - name: app-src
          emptyDir: {}
