apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: demo
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis:alpine