apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: Secret
metadata:
  name: quick-pass
  namespace: demo
type: Opaque
data:
  password: QW5keUh1MTExMSE=

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: demo
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/andy-mariadb-data
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: demo
spec:
  volumeName: mariadb-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-scripts
  namespace: demo
data:
  00-init.sql: |
    CREATE TABLE semifinalists (teams text);
  01-teams.sql: |
    INSERT INTO semifinalists VALUES ('China');
    INSERT INTO semifinalists VALUES ('France');
    INSERT INTO semifinalists VALUES ('Canada');

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: andy-db
  namespace: demo
spec:
  selector:
    matchLabels:
      app: andy-db
  template:
    metadata:
      labels:
        app: andy-db
    spec:
      containers:
        - name: andy-db
          image: mariadb:10.6.8-focal
          env:
            - name: MARIADB_DATABASE
              value: andy-db
            - name: MARIADB_USER
              value: andy
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quick-pass
                  key: password
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quick-pass
                  key: password
          volumeMounts:
            - name: mariadata
              mountPath: /var/lib/mysql
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mariadata
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: init-scripts
          configMap:
            name: db-init-scripts

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: demo
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis:alpine

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: andyyelinhu/world-cup-demo:andydb
          env:
            - name: MARIA_HOST
              value: 'db-service.demo.svc.cluster.local'
            - name: MARIA_USER
              value: root
            - name: MARIA_PASS
              valueFrom:
                secretKeyRef:
                  name: quick-pass
                  key: password
            - name: WELCOME
              value: Welcome to FIFA World Cup 2022!! Lets talk about semifinalists ...
      #     volumeMounts:
      #       - name: app-src
      #         mountPath: /app/app.py
      # volumes:
      #   - name: app-src
      #     emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: demo
spec:
  selector:
    app: andy-db
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: demo
spec:
  selector:
    app: cache
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service 
metadata:
  name: app-service
  namespace: demo
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  # dependsOn:
  #   - name: cache-service
  #   - name: db-service