# apiVersion: v1
# kind: Namespace
# metadata:
#   name: andy-demo

# ---

# apiVersion: v1
# kind: Secret
# metadata:
#   name: quick-pass
#   namespace: andy-demo
# type: Opaque
# data:
#   password: QW5keUh1MTExMSE=

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mariadb-pv
#   namespace: andy-demo
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   storageClassName: standard 
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: /path/andy-mariadb-data
#     type: DirectoryOrCreate

# ---

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mariadb-pvc
#   namespace: andy-demo
# spec:
#   volumeName: mariadb-pv
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: standard
#   resources:
#     requests:
#       storage: 1Gi

# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: db-init-scripts
#   namespace: andy-demo
# data:
#   01-goat.sql: |
#     DROP TABLE IF EXISTS goatplayers;
#     CREATE TABLE goatplayers (player text);
#     INSERT INTO goatplayers VALUES ('MJ');
#     INSERT INTO goatplayers VALUES ('LBJ');
#     INSERT INTO goatplayers VALUES ('KOBE');
#     INSERT INTO goatplayers VALUES ('Shaq');
#     INSERT INTO goatplayers VALUES ('Tim Duncan');
    


# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: andy-db
#   namespace: andy-demo
# spec:
#   selector:
#     matchLabels:
#       app: andy-db
#   template:
#     metadata:
#       labels:
#         app: andy-db
#     spec:
#       containers:
#         - name: andy-db
#           image: mariadb:10.6.8-focal
#           env:
#             - name: MARIADB_DATABASE
#               value: andy-db
#             - name: MARIADB_USER
#               value: andy
#             - name: MARIADB_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: quick-pass
#                   key: password
#             - name: MARIADB_ROOT_PASSWORD
#               valueFrom:
#                 secretKeyRef:
#                   name: quick-pass
#                   key: password
#           # volumeMounts:
#           #   - name: mariadata
#           #     mountPath: /var/lib/mysql
#             - name: init-scripts
#               mountPath: /docker-entrypoint-initdb.d
#       volumes:
#         # - name: mariadata
#         #   persistentVolumeClaim:
#         #     claimName: mariadb-pvc
#         - name: init-scripts
#           configMap:
#             name: db-init-scripts

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: cache
#   namespace: andy-demo
# spec:
#   selector:
#     matchLabels:
#       app: cache
#   template:
#     metadata:
#       labels:
#         app: cache
#     spec:
#       containers:
#         - name: cache
#           image: redis:alpine

# ---

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app
#   namespace: andy-demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: app
#   template:
#     metadata:
#       labels:
#         app: app
#     spec:
#       containers:
#         - name: app
#           image: andyyelinhu/nba-demo:2
#           env:
#             - name: MARIA_HOST
#               value: 'db-service.andy-demo.svc.cluster.local'
#             - name: MARIA_USER
#               value: root
#             - name: MARIA_PASS
#               valueFrom:
#                 secretKeyRef:
#                   name: quick-pass
#                   key: password
#             - name: WELCOME
#               value: Welcome to Andy Hu's NBA Top 5 GOAT Player rating!!!!! 


# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: db-service
#   namespace: andy-demo
# spec:
#   selector:
#     app: andy-db
#   type: LoadBalancer
#   ports:
#     - protocol: "TCP"
#       port: 3306
#       targetPort: 3306

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: cache-service
#   namespace: andy-demo
# spec:
#   selector:
#     app: cache
#   type: ClusterIP
#   ports:
#     - protocol: "TCP"
#       port: 6379
#       targetPort: 6379

# ---

# apiVersion: v1
# kind: Service 
# metadata:
#   name: app-service
#   namespace: andy-demo
# spec:
#   selector:
#     app: app
#   type: LoadBalancer
#   ports:
#     - protocol: "TCP"
#       port: 5000
#       targetPort: 5000
