apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: Secret
metadata:
  name: quickstart-maria-pass
  namespace: demo
type: Opaque
data:
  password: bGpwMjc1Y2w3ejRjdnd2bnBmZHI5bHpsNWhyem16eHI4emN6cjJjZG14aHJicnBsbTdxYzho

---

apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: demo
spec:
  selector:
    app: db
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: demo
spec:
  selector:
    app: cache
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379

---

apiVersion: v1
kind: Service 
metadata:
  name: app-service
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - protocol: "HTTP"
      port: 5000
      targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: demo
spec:
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mariadb:10.6.8-focal
          env:
            - name: MARIADB_DATABASE
              value: demo-db
            - name: MARIADB_USER
              value: maria
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-maria-pass
                  key: token
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-maria-pass
                  key: token
          volumeMounts:
            - name: mariadata
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadata
          persistentVolumeClaim:
            claimName: mariadata


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: demo
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: redis:alpine
          # ports:
          #   - name: redis
          #     containerPort: 6379

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: demo
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: //to be filled
          env:
            - name: MARIA_USER
              value: root
            - name: MARIA_PASS
              valueFrom:
                secretKeyRef:
                  name: quickstart-maria-pass
                  key: token
            - name: WELCOME
              value: Welcome to FIFA World Cup 2022!! Lets talk about semifinalists ...
          volumeMounts:
            - name: app-src
              mountPath: /app
      volumes:
        - name: app-src