name: deploy on local minikube cluster
on:
  push:
    branches: 
      - main
    paths:
      - 'app.py'
      - 'Kubernetes/**'
  workflow_dispatch:    

jobs:
  deploy_and_check_pods:
    runs-on: self-hosted

    steps:
      - name: start minikube
        run: minikube start

      - name: Apply Kubernetes Manifest
        run: |
          cd /Users/andyhu/Documents/Generac/andy-k8s-learning-demo/Kubernetes
          ls
          kubectl apply -f demo.yml
      
      - name: Check Pods
        run: kubectl get pods -n andy-demo

      